version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bambooDB
      POSTGRES_USER: bamboo
      POSTGRES_PASSWORD: BambooAsesores2024
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  traccar:
    image: traccar/traccar:6.6-ubuntu
    ports:
      - "8082:8082"   # Web Interface
      - "5055:5055"   # GPS devices port (Teltonika)
      - "5001:5001"   # Additional GPS port
      - "5002:5002"   # Additional GPS port
      - "5003:5003"   # Additional GPS port
      - "5004:5004"   # Additional GPS port
    volumes:
      - ./traccar-config:/opt/traccar/conf
      - ./traccar-logs:/opt/traccar/logs
      - traccar_data:/opt/traccar/data
    environment:
      - TRACCAR_CONFIG_FILE=/opt/traccar/conf/traccar.xml
      # Configuración para nginx-proxy
      - VIRTUAL_HOST=gps.qarpana.com.ar
      - VIRTUAL_PORT=8082
      - LETSENCRYPT_HOST=gps.qarpana.com.ar
      - LETSENCRYPT_EMAIL=tu@email.com
    networks:
      - app-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build: ./gestion-riego-backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=bamboo
      - DB_HOST=db
      - DB_NAME=bambooDB
      - DB_PASSWORD=BambooAsesores2024
      - DB_PORT=5432
      - JWT_SECRET=tu_clave_secreta_muy_segura
      #- CORS_ORIGIN=http://localhost:3000
      #- VIRTUAL_HOST=localhost:5000

      #comentar la parte de arriba  

      - CORS_ORIGIN=https://qarpana.com.ar  
      - VIRTUAL_HOST=api.qarpana.com.ar 
      - TRACCAR_URL=http://traccar:8082
      - TRACCAR_USER=admin
      - TRACCAR_PASSWORD=admin
      - TRACCAR_WEBHOOK_TOKEN=mi-token-secreto-123
    depends_on:
      - db
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./gestion-riego-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      #- REACT_APP_API_URL=http://localhost:5000
      #comentar la parte de arriba
      - VIRTUAL_HOST=qarpana.com.ar
      - VIRTUAL_PORT=3000
    networks:
      - app-network
    #volumes:
      #- C:\Users\busta\OneDrive\Documentos\Bamboo\Webapp\gestion-riego-pwa\gestion-riego-frontend:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  acme-companion:
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL=tu@email.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

volumes:
  certs:
  vhost:
  html:
  acme:
  postgres_data:
    driver: local
  traccar_data:
    driver: local