# gestion-riego-frontend/Dockerfile
FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY manifest.json ./public/
COPY service-worker.js ./public/

COPY . .

RUN npm install -g react-scripts

# Cambiar permisos
RUN chmod 755 /app/build && \
    chmod 755 /app/public


RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]