# gestion-riego-frontend/Dockerfile
FROM node:18

WORKDIR /app


RUN npm install -g react-scripts

RUN npm install -g serve

# Cambiar permisos
RUN chmod -R 777 /app
COPY package*.json ./

RUN npm install

COPY manifest.json ./public/
COPY service-worker.js ./public/

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "tcp://0.0.0.0:3000"]

